### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Foxy6670** [synesthesiam/magicpy#1]
Every time I try to run `./example.sh`, this happens:

```
Traceback (most recent call last):
  File "/home/user/magicpy/magicpy.py", line 53, in <module>
    pattern = gen_pattern(pattern_width, depth_map.size[1])
  File "/home/user/magicpy/magicpy.py", line 27, in gen_pattern
    return numpy.random.randint(0, 256, (width, height))
  File "mtrand.pyx", line 765, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1256, in numpy.random._bounded_integers._rand_int64
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by cmahnke** [comment]
This is related to the fact, that the calculation of the patterns with returned a float value, replace:
```
pattern_width = depth_map.size[0] / args.pattern_div
```

with:
```
pattern_width = int(depth_map.size[0] / args.pattern_div)
```

You are almost certainly are using Python 3 the code is written for Python 2, you'll need to fix few more things:
* Replace `xrange` with `range`
* Cast values from the `pattern` array to int, since Numpy uses a different `int` internally.:
  ```
  int(pattern[x, y])
  ```

**Comment by forthrin** [comment]
@synesthesiam: Apply this patch and add installation instructions?

```python
diff --git a/magicpy.py b/magicpy.py
index 42b9027..b210675 100644
--- a/magicpy.py
+++ b/magicpy.py
@@ -26,2 +26,3 @@ from PIL import Image
 def gen_pattern(width, height):
+    return numpy.random.randint(0, 256, (int(width), int(height)))
     return numpy.random.randint(0, 256, (width, height))
@@ -55,7 +56,7 @@ if __name__ == '__main__':
     # Create stereogram
-    for x in xrange(0, depth_map.size[0]):
-        for y in xrange(0, depth_map.size[1]):
+    for x in range(0, depth_map.size[0]):
+        for y in range(0, depth_map.size[1]):
 
             if x < pattern_width:
-                out_data[x, y] = pattern[x, y]  # Use generated pattern
+                out_data[x, y] = int(pattern[x, y])  # Use generated pattern
             else:
```

```bash
pbpaste | git apply
pip install numpy pillow
```
